Add linter
NoCountryForGeeks/prisma-graphql-react-next-example pull request #3
Opened 2018-12-24 11:43 UTC by IvanRodriCalleja

- Added linter to solution and command

**Note: The linter is not executed in the nodemon process**

I could't execute both commands "babel-node" and "lint" from nodemon. Do you know how execute both commands at same time?
I tried ```"dotenv -- nodemon ./src/index.js --inspect --exec \"babel-node && yarn lint\" -e js"``` and similar commands but nothing worked.

2018-12-24 15:02 UTC, acnagrellos approved these changes

2018-12-24 15:28 UTC, franmolmedo requested changes

2018-12-24 15:28 UTC, franmolmedo commented on package.json
>      "start": "dotenv -- nodemon ./src/index.js --inspect --exec babel-node -e js",
Node execution at the end. Call first lint

2018-12-24 15:28 UTC, franmolmedo commented on src/index.js
> +      debug: true
Get this value depending on environment

2018-12-24 15:28 UTC, franmolmedo commented on .eslintrc
> +    },
Add test

2018-12-24 15:28 UTC, franmolmedo commented on .eslintrc
> +}
Keep the default rules from recommended package

2018-12-24 15:28 UTC, franmolmedo commented on package.json
> +  },
If we are using Babel node why you set the requirements so high?

2018-12-24 15:28 UTC, franmolmedo commented on package.json
>      "start": "dotenv -- nodemon ./src/index.js --inspect --exec babel-node -e js",
Do we need Babel node? I think you are using it only for imports

2018-12-24 16:58 UTC, IvanRodriCalleja commented on package.json
>      "start": "dotenv -- nodemon ./src/index.js --inspect --exec babel-node -e js",
Yes, the main reasson is to can use "imports".  Do you prefer to remove it?

2018-12-24 17:00 UTC, IvanRodriCalleja commented on src/index.js
> +      debug: true
The change is to remove the "," because the linter throw a warning, the value is changed in the #2. Here only there are changes for linter

2018-12-24 17:02 UTC, IvanRodriCalleja commented on package.json
> +  },
Should i set the version 6.0.0?

2018-12-24 18:00 UTC, franmolmedo commented on package.json
> +  },
LTS version

2019-01-03 09:44 UTC, franmolmedo approved these changes

2019-01-03 11:00 UTC, merged